todos los ejercicios, .gitignore, learn.json
4GeeksAcademy/python-http-requests-api-tutorial-exercises pull request #24
Opened 2024-04-05 13:35 UTC by josemoracard

se ignoraron los archivos de pycache
se añadieron todos los solution
se removió en el learn.json la single quote ' que hacía que los tests no pudiera correr

2024-04-05 14:57 UTC, tommygonzaleza requested changes

2024-04-05 14:57 UTC, tommygonzaleza commented on exercises/00-welcome/README.es.md
> +1. Cómo hacer solicitudes GET.
Signos de interrogacion

2024-04-05 14:57 UTC, tommygonzaleza commented on exercises/00-welcome/README.md
> +1. How to do GET requests.
Signos de interrogacion

2024-04-05 14:57 UTC, tommygonzaleza commented on exercises/00-welcome/README.md
> +Python Requests is the most popular package for consuming APIs and doing HTTP requests.
Desarrolla un poco mas una introduccion al uso de APIs con python

2024-04-05 14:57 UTC, tommygonzaleza commented on exercises/00-welcome/README.es.md
> +Python Requests es el paquete más popular para consumir APIs y hacer solicitudes HTTP.
Desarrolla un poco mas una introduccion al uso de APIs con python

2024-04-05 19:21 UTC, josemoracard commented on exercises/00-welcome/README.es.md
> +1. Cómo hacer solicitudes GET.
done

2024-04-05 19:21 UTC, josemoracard commented on exercises/00-welcome/README.md
> +1. How to do GET requests.
done

2024-04-08 15:43 UTC, josemoracard commented on exercises/00-welcome/README.md
> +Python Requests is the most popular package for consuming APIs and doing HTTP requests.
done

2024-04-08 15:43 UTC, josemoracard commented on exercises/00-welcome/README.es.md
> +Python Requests es el paquete más popular para consumir APIs y hacer solicitudes HTTP.
done

2024-04-10 18:55 UTC, tommygonzaleza approved these changes

2024-05-07 20:12 UTC, merged